### ISSUE TITLE
Not JSON serializable

### ISSUE THREAD

**Issue by CaledoniaProject** [securifybv/ShellLink#4]
I'm using the following code to serialize data:

```
ShellLink.Shortcut shortcut = ShellLink.Shortcut.ReadFromFile(path);
string data = JsonConvert.SerializeObject(shortcut);
Debug.WriteLine(data);
```

And it raises exception:

```
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'ShellLinkHeader' with type 'ShellLink.Shortcut'. Path ''.
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
```

It might be necessary to add several `[JsonIgnore]` tags.

**Comment by ykoster** [comment]
Hi @CaledoniaProject, this code was never created with serialization in mind. The error you're getting is because the Shortcut class references to itself:

https://github.com/securifybv/ShellLink/blob/aafc363a331244042dafd430ab1131d131d47a08/ShellLink/Shortcut.cs#L36

What are you trying to accomplish?

**Comment by CaledoniaProject** [comment]
I parse the LNK on the Windows client and display it somewhere else.

As a temporary workaround, I created a dictionary from StringData, ExtraData and LinkInfo, then serialized the dictionary.

**Comment by ykoster** [comment]
You can ignore the self reference with the `ReferenceLoopHandling.Ignore` setting:

```c#
string data = JsonConvert.SerializeObject(shortcut,
	Formatting.Indented,
	new JsonSerializerSettings {
		ReferenceLoopHandling = ReferenceLoopHandling.Ignore
});
```

**Comment by CaledoniaProject** [comment]
Nice, didn't know that
